# Generated by Django 5.1.3 on 2025-02-08 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('capacidad', models.IntegerField(default=12, help_text='Default 12')),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('tipo', models.CharField(choices=[('torneo', 'Torneo'), ('entrenamiento', 'Entrenamiento')], max_length=20)),
                ('costo', models.IntegerField(blank=True, help_text='Solo para torneos', null=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Null si es torneo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.categoria')),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.IntegerField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.categoria')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos.pago')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_torneo', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('presente', 'Presente'), ('ausente', 'Ausente')], default='pendiente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_entrenamiento', to='eventos.evento')),
            ],
        ),
    ]
