# Generated by Django 5.1.3 on 2025-02-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
