# Generated by Django 5.1.3 on 2025-02-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('bola-roja', 'Bola Roja'), ('bola-naranja', 'Bola Naranja'), ('bola-verde', 'Bola Verde'), ('sub-14', 'Sub 14'), ('sub-16', 'Sub 16'), ('sub-21', 'Sub 21'), ('basico', 'Basico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=100, unique=True),
        ),
    ]
