# Generated by Django 5.1.3 on 2025-02-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, choices=[('activo', 'activo'), ('eliminado', 'eliminado'), ('retirado', 'retirado')], max_length=20, null=True),
        ),
    ]
